### PR TITLE
Please merge this, it only modifies the Readme

### PR DESCRIPTION
**Pull request by mbiarnes**
This PR (commit) can be reverted.
This PR is to verify if the Jenkins Job that publishes the optaplanner-website in a Docker container is triggered after this PR was merged.

### CODE REVIEW

**Comment by psiroky** [comment]
@mbiarnes you don't need new commits to test that the the job is triggered. If will automatically execute new build if there are no build yet.

**Comment by mbiarnes** [comment]
@psiroky I don't understand completely. The job https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Empty/job/optaplanner-website-automatic-publishing/ "looks" if there is a new PR. I want to assure that only if this PR was merged that the pulishing job is triggered.

**Comment by psiroky** [comment]
@mbiarnes sorry, I am getting a bit confused here. I am not sure we should be monitoring PR jobs. What happens if someone pushes changes directly? We still want the publish to happen. Also the job configuration seems to be watching the job results, no the actual status. We should not run the publish job until there are changes (e.g. merged PR). Or is there something I am missing?

**Comment by mbiarnes** [comment]
@psiroky I hope it looks better now ...

**Pull request merged**
